In [53]:
import model
import torch
import torch.nn as nn
import torch.optim as optim

In [54]:
embed_dim = 16  # Embedding dimension
num_heads = 4  # Number of attention heads
num_layers = 2  # Number of transformer layers
dropout = 0.1  # Dropout rate
graph_colomns=10
num_components=5
batch_size = 16  # Batch size

graph_input_dim = 4  # Number of colomns in the graph
text_vocab_size = 26  # Vocabulary size for text

In [55]:
model = model.GraphToTextTransformer(
    graph_input_dim, 
    text_vocab_size, 
    embed_dim, 
    num_heads, 
    num_layers, 
    dropout)

c:\Users\MSI\miniconda3\envs\ml\lib\site-packages\torch\nn\modules\transformer.py:379: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance)
  warnings.warn(


In [56]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)

In [57]:
learning_rate = 0.001
num_epochs = 10000

# Define loss function and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

Sample trainig set

In [59]:
num_ciruits = 100
graph_dataset =  torch.randn(num_ciruits, graph_input_dim ,graph_colomns)
text_dataset = torch.randint(0, text_vocab_size, (num_ciruits,graph_colomns))

graph_dataset = graph_dataset.to(device)
text_dataset = text_dataset.to(device)
graph_dataset[0]

tensor([[ 2.3307, -1.5095, -1.4843, -0.4999,  1.4887, -0.1779,  1.2681, -1.1204,
          0.0378,  0.3462],
        [ 0.2207, -0.7933,  1.7423,  0.2474,  0.4381,  0.1984,  1.2810,  1.3318,
         -1.8038,  1.5678],
        [ 0.5153,  1.3495, -0.2386,  1.8695, -0.6617, -1.5935, -0.5174, -0.9140,
         -0.2316, -0.3357],
        [-0.9725,  1.7797,  0.2588, -0.2168,  0.3867,  0.2882, -0.7758, -1.8476,
          0.2508,  0.4474]], device='cuda:0')

Split data in to test and train set

In [ ]:
from sklearn.model_selection import train_test_split

graph_train, graph_test, text_train, text_test = train_test_split(graph_dataset, text_dataset, test_size=0.2)



In [ ]:
graph_dataset[0], 


(tensor([[-0.1505, -1.8847,  0.5436, -0.7566],
         [ 0.2692,  0.5258, -2.3234,  0.3013],
         [ 1.8111,  1.1219, -2.0301, -1.0109],
         [ 0.4073,  0.2593, -0.8126,  1.1230],
         [ 0.5222, -0.1484,  0.7408, -0.8330],
         [ 0.0088, -0.0660,  0.5487, -0.3931],
         [-0.0306, -0.0156, -1.0376, -2.5064],
         [ 0.5291, -0.0033, -0.6040, -2.3976],
         [ 0.9942,  0.4102, -1.1314,  1.8493],
         [ 0.8991,  0.7321, -1.2880, -2.1208]], device='cuda:0'),)

In [ ]:
# Training loop
for epoch in range(num_epochs):
    model.train()  # Set the model to training mode

    # Forward pass
    for i in range(0, len(graph_train), batch_size):
        graph_data = graph_train[i:i+batch_size]
        text = text_train[i:i+batch_size]

        target = text[:, 1:].reshape(-1)  # Exclude the first token for target
        print(target)
        input = text[:, :-1]

    
    output = model(graph_data, text_input[:, :-1])  # Exclude the last token for input
    output = output.reshape(-1, text_vocab_size)  # Reshape for loss calculation
    # Take vocab index probabilistically


    target = text_input[:, 1:].reshape(-1)  # Exclude the first token for target

    # Compute loss
    loss = criterion(output, target)

    # Backward pass and optimization
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()


    # Print loss for the epoch
    if (epoch + 1) % 100 == 0:  # Print every 100 epochs
        print(f"Epoch [{epoch + 1}/{num_epochs}], Loss: {loss.item():.4f}")

tensor([11, 17, 19,  ..., 20, 13, 14], device='cuda:0')


NameError: name 'text_input' is not defined